#!/usr/bin/env bash

brew update

brew upgrade --all

# From github: mathiasbynens/dotfiles
brew install bash
brew tap homebrew/versions
brew install bash-completion2

if ! fgrep -q '/usr/local/bin/bash' /etc/shells; then
  echo '/usr/local/bin/bash' | sudo tee -a /etc/shells;
  chsh -s /usr/local/bin/bash;
fi;

brew install wget --with-iri
brew install vim --override-system-vi
brew install homebrew/dupes/grep
brew install homebrew/dupes/openssh
brew install homebrew/dupes/screen

# Install font tools.
brew tap bramstein/webfonttools
brew install sfnt2woff
brew install sfnt2woff-zopfli
brew install woff2

# Misc tools
brew install trash
brew install httpie
brew install jq
brew install the_silver_searcher
brew install trash

# Dev tools
brew install hub
brew install git-extras
brew install reattach-to-user-namespace --with-wrap-pbcopy-and-pbpaste
brew install aws
brew install awscli
brew install amazon-ecs-cli
brew install foreman
brew install node

# Databases
brew install postgresql
brew install redis
brew install mongodb

# Server tools
brew install imagemagick
brew install libsass
brew install libxmlsec1

# Ad hoc (not categorized stuff)
