#!/usr/bin/env bash

brew update

brew upgrade --all

brew tap homebrew/versions
brew install bash
brew install bash-completion2

brew install wget --with-iri
brew install vim --override-system-vi
brew install tmux
berw install zsh
brew install grep
brew install openssh

# Misc tools
brew install trash
brew install httpie
brew install jq
brew install the_silver_searcher
brew install trash

# Dev tools
brew install git
brew install git-lfs
brew install gradle
brew install python
brew install python-3
brew install hub
brew install git-extras
brew install aws
brew install awscli
brew install amazon-ecs-cli
brew install foreman
brew install node
brew install heroku

# Databases
brew install postgresql
brew install redis

# Server tools
brew install imagemagick
brew install libsass
brew install libxmlsec1
